# Generated by Django 6.0.3 on 2026-03-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schl_id', models.IntegerField(unique=True)),
                ('schl_name', models.CharField(max_length=30)),
            ],
        ),
    ]
